### ISSUE TITLE
Result of execution displays fields not in order of query request

### ISSUE THREAD

**Issue by edsalat** [nfl/graphql-rxjava#1]
Result of execution displays fields not in order of query request,,
For example if I ask for "user {firstName, lastName}
resulting JSON could be "user":{"lastName":"Smith", "firstName":"Alex"}
It's a big problem since graphql should control order of fields by query

**Comment by tberman** [comment]
Where does it say that in the GraphQL spec?

I did a quick read and missed it, also this is likely a bug against graphql-java proper if it is one at all.
